services:
  site:
    build: .
    volumes:
      - ./content:/site/content
      - ./templates:/site/templates
      - site_output:/site/_site

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - site_output:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - site

volumes:
  site_output: